/**
 * Generated by the official oasdiff v1.29.1 executable (`oasdiff schema`).
 * Release commit: 2bb87bada404d350cb56e5504e8bd5d76f6159bf
 * Exact command stdout SHA-256:
 * c414492d132fbc2a4b230a3ebd90bebbd2f4fd51b2e44ac58e00620a89561647
 * Upstream license: Apache-2.0
 */
export const OASDIFF_RAW_SCHEMA = {
  $schema: "https://json-schema.org/draft/2020-12/schema",
  $id: "https://github.com/oasdiff/oasdiff/formatters/changes",
  $ref: "#/$defs/Changes",
  $defs: {
    Change: {
      properties: {
        id: { type: "string" },
        text: { type: "string" },
        comment: { type: "string" },
        disclaimers: { items: { type: "string" }, type: "array" },
        level: { type: "integer" },
        operation: { type: "string" },
        operationId: { type: "string" },
        path: { type: "string" },
        section: { type: "string" },
        attributes: { type: "object" },
        baseSource: { $ref: "#/$defs/Source" },
        revisionSource: { $ref: "#/$defs/Source" },
        fingerprint: { type: "string" },
      },
      additionalProperties: false,
      type: "object",
      required: ["level"],
    },
    Changes: { items: { $ref: "#/$defs/Change" }, type: "array" },
    Source: {
      properties: {
        file: { type: "string" },
        line: { type: "integer" },
        column: { type: "integer" },
        endLine: { type: "integer" },
        endColumn: { type: "integer" },
      },
      additionalProperties: false,
      type: "object",
    },
  },
} as const;

export const OASDIFF_RAW_SCHEMA_STDOUT_SHA256 =
  "c414492d132fbc2a4b230a3ebd90bebbd2f4fd51b2e44ac58e00620a89561647";

export const OASDIFF_UPSTREAM_METADATA = Object.freeze({
  repository: "https://github.com/oasdiff/oasdiff",
  release: "v1.29.1",
  commit: "2bb87bada404d350cb56e5504e8bd5d76f6159bf",
  licenseSpdx: "Apache-2.0",
  releaseArchiveLicenseSha256:
    "c71d239df91726fc519c6eb72d318ec65820627232b2f796219e87dcf35d0ab4",
});
